use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum KeyCode {
    // Mouse buttons
    LButton,
    RButton,
    MButton,
    XButton1,
    XButton2,

    // Standard keys
    Backspace,
    Tab,
    Clear,
    Enter,
    Return,
    Shift,
    Control,
    Ctrl,
    Alt,
    Pause,
    CapsLock,
    Escape,
    Esc,
    Space,
    PageUp,
    PageDown,
    End,
    Home,
    Left,
    Up,
    Right,
    Down,
    Select,
    Print,
    Execute,
    PrintScreen,
    Insert,
    Delete,
    Del,
    Help,

    // Number keys
    #[serde(rename = "0")]
    Key0,
    #[serde(rename = "1")]
    Key1,
    #[serde(rename = "2")]
    Key2,
    #[serde(rename = "3")]
    Key3,
    #[serde(rename = "4")]
    Key4,
    #[serde(rename = "5")]
    Key5,
    #[serde(rename = "6")]
    Key6,
    #[serde(rename = "7")]
    Key7,
    #[serde(rename = "8")]
    Key8,
    #[serde(rename = "9")]
    Key9,

    // Letter keys
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,

    // Windows keys
    LWin,
    RWin,
    Apps,
    Sleep,

    // Numpad
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    Multiply,
    Add,
    Separator,
    Subtract,
    Decimal,
    Divide,

    // Function keys
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,

    // Numlock and scroll lock
    NumLock,
    ScrollLock,

    // Shift/Ctrl/Alt variants
    LShift,
    RShift,
    LControl,
    RControl,
    LAlt,
    RAlt,

    // Browser keys
    BrowserBack,
    BrowserForward,
    BrowserRefresh,
    BrowserStop,
    BrowserSearch,
    BrowserFavorites,
    BrowserHome,

    // Volume and media
    VolumeMute,
    VolumeDown,
    VolumeUp,
    MediaNextTrack,
    MediaPrevTrack,
    MediaStop,
    MediaPlayPause,
    LaunchMail,
    LaunchMediaSelect,
    LaunchApp1,
    LaunchApp2,

    // OEM keys
    OemSemicolon,
    OemEquals,
    OemComma,
    OemMinus,
    OemPeriod,
    OemSlash,
    OemBacktick,
    OemLBracket,
    OemBackslash,
    OemRBracket,
    OemQuote,
}

impl KeyCode {
    pub fn code(&self) -> u32 {
        match self {
            KeyCode::LButton => 0x01,
            KeyCode::RButton => 0x02,
            KeyCode::MButton => 0x04,
            KeyCode::XButton1 => 0x05,
            KeyCode::XButton2 => 0x06,

            KeyCode::Backspace => 0x08,
            KeyCode::Tab => 0x09,
            KeyCode::Clear => 0x0C,
            KeyCode::Enter | KeyCode::Return => 0x0D,
            KeyCode::Shift => 0x10,
            KeyCode::Control | KeyCode::Ctrl => 0x11,
            KeyCode::Alt => 0x12,
            KeyCode::Pause => 0x13,
            KeyCode::CapsLock => 0x14,
            KeyCode::Escape | KeyCode::Esc => 0x1B,
            KeyCode::Space => 0x20,
            KeyCode::PageUp => 0x21,
            KeyCode::PageDown => 0x22,
            KeyCode::End => 0x23,
            KeyCode::Home => 0x24,
            KeyCode::Left => 0x25,
            KeyCode::Up => 0x26,
            KeyCode::Right => 0x27,
            KeyCode::Down => 0x28,
            KeyCode::Select => 0x29,
            KeyCode::Print => 0x2A,
            KeyCode::Execute => 0x2B,
            KeyCode::PrintScreen => 0x2C,
            KeyCode::Insert => 0x2D,
            KeyCode::Delete | KeyCode::Del => 0x2E,
            KeyCode::Help => 0x2F,

            KeyCode::Key0 => 0x30,
            KeyCode::Key1 => 0x31,
            KeyCode::Key2 => 0x32,
            KeyCode::Key3 => 0x33,
            KeyCode::Key4 => 0x34,
            KeyCode::Key5 => 0x35,
            KeyCode::Key6 => 0x36,
            KeyCode::Key7 => 0x37,
            KeyCode::Key8 => 0x38,
            KeyCode::Key9 => 0x39,

            KeyCode::A => 0x41,
            KeyCode::B => 0x42,
            KeyCode::C => 0x43,
            KeyCode::D => 0x44,
            KeyCode::E => 0x45,
            KeyCode::F => 0x46,
            KeyCode::G => 0x47,
            KeyCode::H => 0x48,
            KeyCode::I => 0x49,
            KeyCode::J => 0x4A,
            KeyCode::K => 0x4B,
            KeyCode::L => 0x4C,
            KeyCode::M => 0x4D,
            KeyCode::N => 0x4E,
            KeyCode::O => 0x4F,
            KeyCode::P => 0x50,
            KeyCode::Q => 0x51,
            KeyCode::R => 0x52,
            KeyCode::S => 0x53,
            KeyCode::T => 0x54,
            KeyCode::U => 0x55,
            KeyCode::V => 0x56,
            KeyCode::W => 0x57,
            KeyCode::X => 0x58,
            KeyCode::Y => 0x59,
            KeyCode::Z => 0x5A,

            KeyCode::LWin => 0x5B,
            KeyCode::RWin => 0x5C,
            KeyCode::Apps => 0x5D,
            KeyCode::Sleep => 0x5F,

            KeyCode::Numpad0 => 0x60,
            KeyCode::Numpad1 => 0x61,
            KeyCode::Numpad2 => 0x62,
            KeyCode::Numpad3 => 0x63,
            KeyCode::Numpad4 => 0x64,
            KeyCode::Numpad5 => 0x65,
            KeyCode::Numpad6 => 0x66,
            KeyCode::Numpad7 => 0x67,
            KeyCode::Numpad8 => 0x68,
            KeyCode::Numpad9 => 0x69,
            KeyCode::Multiply => 0x6A,
            KeyCode::Add => 0x6B,
            KeyCode::Separator => 0x6C,
            KeyCode::Subtract => 0x6D,
            KeyCode::Decimal => 0x6E,
            KeyCode::Divide => 0x6F,

            KeyCode::F1 => 0x70,
            KeyCode::F2 => 0x71,
            KeyCode::F3 => 0x72,
            KeyCode::F4 => 0x73,
            KeyCode::F5 => 0x74,
            KeyCode::F6 => 0x75,
            KeyCode::F7 => 0x76,
            KeyCode::F8 => 0x77,
            KeyCode::F9 => 0x78,
            KeyCode::F10 => 0x79,
            KeyCode::F11 => 0x7A,
            KeyCode::F12 => 0x7B,
            KeyCode::F13 => 0x7C,
            KeyCode::F14 => 0x7D,
            KeyCode::F15 => 0x7E,
            KeyCode::F16 => 0x7F,
            KeyCode::F17 => 0x80,
            KeyCode::F18 => 0x81,
            KeyCode::F19 => 0x82,
            KeyCode::F20 => 0x83,
            KeyCode::F21 => 0x84,
            KeyCode::F22 => 0x85,
            KeyCode::F23 => 0x86,
            KeyCode::F24 => 0x87,

            KeyCode::NumLock => 0x90,
            KeyCode::ScrollLock => 0x91,

            KeyCode::LShift => 0xA0,
            KeyCode::RShift => 0xA1,
            KeyCode::LControl => 0xA2,
            KeyCode::RControl => 0xA3,
            KeyCode::LAlt => 0xA4,
            KeyCode::RAlt => 0xA5,

            KeyCode::BrowserBack => 0xA6,
            KeyCode::BrowserForward => 0xA7,
            KeyCode::BrowserRefresh => 0xA8,
            KeyCode::BrowserStop => 0xA9,
            KeyCode::BrowserSearch => 0xAA,
            KeyCode::BrowserFavorites => 0xAB,
            KeyCode::BrowserHome => 0xAC,

            KeyCode::VolumeMute => 0xAD,
            KeyCode::VolumeDown => 0xAE,
            KeyCode::VolumeUp => 0xAF,
            KeyCode::MediaNextTrack => 0xB0,
            KeyCode::MediaPrevTrack => 0xB1,
            KeyCode::MediaStop => 0xB2,
            KeyCode::MediaPlayPause => 0xB3,
            KeyCode::LaunchMail => 0xB4,
            KeyCode::LaunchMediaSelect => 0xB5,
            KeyCode::LaunchApp1 => 0xB6,
            KeyCode::LaunchApp2 => 0xB7,

            KeyCode::OemSemicolon => 0xBA,
            KeyCode::OemEquals => 0xBB,
            KeyCode::OemComma => 0xBC,
            KeyCode::OemMinus => 0xBD,
            KeyCode::OemPeriod => 0xBE,
            KeyCode::OemSlash => 0xBF,
            KeyCode::OemBacktick => 0xC0,
            KeyCode::OemLBracket => 0xDB,
            KeyCode::OemBackslash => 0xDC,
            KeyCode::OemRBracket => 0xDD,
            KeyCode::OemQuote => 0xDE,
        }
    }

    #[allow(dead_code)]
    pub fn name(&self) -> &'static str {
        match self {
            KeyCode::LButton => "LButton",
            KeyCode::RButton => "RButton",
            KeyCode::MButton => "MButton",
            KeyCode::XButton1 => "XButton1",
            KeyCode::XButton2 => "XButton2",
            KeyCode::Backspace => "Backspace",
            KeyCode::Tab => "Tab",
            KeyCode::Clear => "Clear",
            KeyCode::Enter | KeyCode::Return => "Enter",
            KeyCode::Shift => "Shift",
            KeyCode::Control | KeyCode::Ctrl => "Ctrl",
            KeyCode::Alt => "Alt",
            KeyCode::Pause => "Pause",
            KeyCode::CapsLock => "CapsLock",
            KeyCode::Escape | KeyCode::Esc => "Esc",
            KeyCode::Space => "Space",
            KeyCode::PageUp => "PageUp",
            KeyCode::PageDown => "PageDown",
            KeyCode::End => "End",
            KeyCode::Home => "Home",
            KeyCode::Left => "Left",
            KeyCode::Up => "Up",
            KeyCode::Right => "Right",
            KeyCode::Down => "Down",
            KeyCode::Select => "Select",
            KeyCode::Print => "Print",
            KeyCode::Execute => "Execute",
            KeyCode::PrintScreen => "PrintScreen",
            KeyCode::Insert => "Insert",
            KeyCode::Delete | KeyCode::Del => "Delete",
            KeyCode::Help => "Help",
            KeyCode::Key0 => "0",
            KeyCode::Key1 => "1",
            KeyCode::Key2 => "2",
            KeyCode::Key3 => "3",
            KeyCode::Key4 => "4",
            KeyCode::Key5 => "5",
            KeyCode::Key6 => "6",
            KeyCode::Key7 => "7",
            KeyCode::Key8 => "8",
            KeyCode::Key9 => "9",
            KeyCode::A => "A",
            KeyCode::B => "B",
            KeyCode::C => "C",
            KeyCode::D => "D",
            KeyCode::E => "E",
            KeyCode::F => "F",
            KeyCode::G => "G",
            KeyCode::H => "H",
            KeyCode::I => "I",
            KeyCode::J => "J",
            KeyCode::K => "K",
            KeyCode::L => "L",
            KeyCode::M => "M",
            KeyCode::N => "N",
            KeyCode::O => "O",
            KeyCode::P => "P",
            KeyCode::Q => "Q",
            KeyCode::R => "R",
            KeyCode::S => "S",
            KeyCode::T => "T",
            KeyCode::U => "U",
            KeyCode::V => "V",
            KeyCode::W => "W",
            KeyCode::X => "X",
            KeyCode::Y => "Y",
            KeyCode::Z => "Z",
            KeyCode::LWin => "LWin",
            KeyCode::RWin => "RWin",
            KeyCode::Apps => "Apps",
            KeyCode::Sleep => "Sleep",
            KeyCode::Numpad0 => "Numpad0",
            KeyCode::Numpad1 => "Numpad1",
            KeyCode::Numpad2 => "Numpad2",
            KeyCode::Numpad3 => "Numpad3",
            KeyCode::Numpad4 => "Numpad4",
            KeyCode::Numpad5 => "Numpad5",
            KeyCode::Numpad6 => "Numpad6",
            KeyCode::Numpad7 => "Numpad7",
            KeyCode::Numpad8 => "Numpad8",
            KeyCode::Numpad9 => "Numpad9",
            KeyCode::Multiply => "Multiply",
            KeyCode::Add => "Add",
            KeyCode::Separator => "Separator",
            KeyCode::Subtract => "Subtract",
            KeyCode::Decimal => "Decimal",
            KeyCode::Divide => "Divide",
            KeyCode::F1 => "F1",
            KeyCode::F2 => "F2",
            KeyCode::F3 => "F3",
            KeyCode::F4 => "F4",
            KeyCode::F5 => "F5",
            KeyCode::F6 => "F6",
            KeyCode::F7 => "F7",
            KeyCode::F8 => "F8",
            KeyCode::F9 => "F9",
            KeyCode::F10 => "F10",
            KeyCode::F11 => "F11",
            KeyCode::F12 => "F12",
            KeyCode::F13 => "F13",
            KeyCode::F14 => "F14",
            KeyCode::F15 => "F15",
            KeyCode::F16 => "F16",
            KeyCode::F17 => "F17",
            KeyCode::F18 => "F18",
            KeyCode::F19 => "F19",
            KeyCode::F20 => "F20",
            KeyCode::F21 => "F21",
            KeyCode::F22 => "F22",
            KeyCode::F23 => "F23",
            KeyCode::F24 => "F24",
            KeyCode::NumLock => "NumLock",
            KeyCode::ScrollLock => "ScrollLock",
            KeyCode::LShift => "LShift",
            KeyCode::RShift => "RShift",
            KeyCode::LAlt => "LAlt",
            KeyCode::RAlt => "RAlt",
            KeyCode::VolumeMute => "VolumeMute",
            KeyCode::VolumeDown => "VolumeDown",
            KeyCode::VolumeUp => "VolumeUp",
            KeyCode::MediaNextTrack => "MediaNextTrack",
            KeyCode::MediaPrevTrack => "MediaPrevTrack",
            KeyCode::MediaStop => "MediaStop",
            KeyCode::MediaPlayPause => "MediaPlayPause",
            KeyCode::LaunchMail => "LaunchMail",
            KeyCode::LaunchMediaSelect => "LaunchMediaSelect",
            KeyCode::LaunchApp1 => "LaunchApp1",
            KeyCode::LaunchApp2 => "LaunchApp2",
            KeyCode::OemSemicolon => ";",
            KeyCode::OemEquals => "=",
            KeyCode::OemComma => ",",
            KeyCode::OemMinus => "-",
            KeyCode::OemPeriod => ".",
            KeyCode::OemSlash => "/",
            KeyCode::OemBacktick => "`",
            KeyCode::OemLBracket => "[",
            KeyCode::OemBackslash => "\\",
            KeyCode::OemRBracket => "]",
            KeyCode::OemQuote => "'",
            KeyCode::LControl => "LCtrl",
            KeyCode::RControl => "RCtrl",
            KeyCode::BrowserBack => "BrowserBack",
            KeyCode::BrowserForward => "BrowserForward",
            KeyCode::BrowserRefresh => "BrowserRefresh",
            KeyCode::BrowserStop => "BrowserStop",
            KeyCode::BrowserSearch => "BrowserSearch",
            KeyCode::BrowserFavorites => "BrowserFavorites",
            KeyCode::BrowserHome => "BrowserHome",
        }
    }
}
