[package]
name = "bouton-windows"
version = "0.1.0"
edition = "2024"

[dependencies]
bouton-core = { workspace = true }
haven = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bincode = { workspace = true }
tokio = { workspace = true }
directories = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.52", features = ["Win32_UI_Input_KeyboardAndMouse"] }
